#!/bin/bash

shopt -s nullglob dotglob; files=(/Applications/Ableton\ Live\ *.app); 
latest_live=${files[@]:(-1)}; 

mv /private/tmp/Dark\ Theme.ask "$latest_live/Contents/App-Resources/Skins/"

exit 0

