#!/bin/bash

shopt -s nullglob dotglob; files=(/Applications/Ableton\ Live\ *.app); 
latest_live=${files[@]:(-1)}; 

mv /private/tmp/APCAdvanced "$latest_live/Contents/App-Resources/MIDI Remote Scripts/APCAdvanced"

exit 0

